pipeline {
    // These are pre-build sections
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // This is build section
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-SG
                            terraform init
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-SG
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') { 
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-SG
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Parallel Trigger') {
            parallel {
                stage('SG-RULES'){
                steps {
                    script {
                        build job: '20-SG-RULES',
                            wait: false, // Wait for completion
                            propagate: false // Propagate status
                }
            }
            }

            stage('ACM') {
                steps {
                    script {
                        build job: '30-ACM',
                            wait: true, // Wait for completion
                            propagate: false // Propagate status
                }
            }
            }
            stage('EKS') {
                steps {
                    script {
                        build job: '50-EKS',
                            wait: false, // Wait for completion
                            propagate: false // Propagate status
                }
            }
            }

            stage('Bastion') {
                steps {
                    script {
                        build job: '60-Bastion',
                            wait: false, // Wait for completion
                            propagate: false // Propagate status
                }
            }
            }


            stage('ECR') {
                steps {
                    script {
                        build job: '70-ECR',
                            wait: false, // Wait for completion
                            propagate: false // Propagate status
                }
            }
            }
            }
        }
        stage('ALB') {
                steps {
                    script {
                        build job: '40-Ingress-ALB',
                            wait: false, // Wait for completion
                            propagate: false // Propagate status
                }
            }
            }
    }
    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}